### PR TITLE
add new driver Op6tSlotDxe for OnePlus 6T (fajita)

### PR DESCRIPTION
**Pull request by longjunyu2**
Add new driver Op6tSlotDxe for OnePlus 6T (fajita) to support A/B slot.

### CODE REVIEW

**Comment by longjunyu2** [comment]
This PR will solve the problem of being stuck in FastBoot mode after starting UEFI several times.
This modification is currently only valid for plus 6T devices.
Request code review because sector operation is involved. :)

**Comment by strongtz** [comment]
@longjunyu2 Will it work on Oneplus 6 (enchilada)?

**Comment by longjunyu2** [comment]
> @longjunyu2 Will it work on Oneplus 6 (enchilada)?

I don't know. We need to test it.

**Review by BigfootACA — COMMENTED** [review]
nice

**Review by strongtz — APPROVED** [review]
It looks good to me.

**Pull request merged**
